# generated by datamodel-codegen:
#   filename:  schema_ext_json_patch_base_v0_0_1.json
#   timestamp: 2025-05-08T06:43:09+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Field, constr


class ExtJsonPatchBase(BaseModel):
    sourceHashes: Dict[
        constr(pattern=r'^[0-9a-zA-Z_-]+$'),
        Optional[constr(pattern=r'^[0-9a-zA-Z]{40,}$')],
    ] = Field(
        ...,
        description='Mapping of aliases to source documents identiied by sha256 hexdigets',
    )
    target: constr(pattern=r'^[0-9a-zA-Z_-]+$') = Field(
        ..., description='Valid name for JSON attribute'
    )
    operations: List = Field(..., description='array of JSON patch operations')
