# generated by datamodel-codegen:
#   filename:  schema_json_document_archive_base_v0_0_1.json
#   timestamp: 2025-03-28T09:21:15+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class JsonDocumentArchiveBase(BaseModel):
    rootPath: Optional[str] = Field(
        ..., description='Path to root directory on filesystem'
    )
    archive: Dict[str, Any] = Field(
        ..., description='Nested collection of JSON document references'
    )
